### PR TITLE
Fix #1221 Lack of ability to automatically generate valid Open API schemas for downloading files

### LINKED ISSUE #1221: Lack of ability to automatically generate valid Open API 3.0 schema for downloading files.
Lack of ability to automatically generate valid Open API 3.0 schema for downloading files.

For example when I have an endpoint returning content type `application/pdf ` (or `image/png`, or ...) and I expect:
```json
{
  "/pdf": {
    "get": {
      "summary": "Get PDF file",
      "parameters": [],
      "responses": {
        "200": {
          "description": "PDF file",
          "content": {
            "application/pdf": {
              "schema": {
                "type": "string",
                "format": "binary"
              }
            }
          }
        },
        "404": {
          "description": "File not found"
        }
      }
    }
  }
}
```

Currently if I try the following:
```
  returning(
      status = OK,
      body = Body.binary(APPLICATION_PDF).toLens() to "pdf".toByteArray().inputStream()
  )
```

I get exception `Caused by: com.github.underscore.Json$ParseException: Unexpected end of input at 1:-1`

### PR DESCRIPTION
**Pull request by hektorKS**
Issue link: https://github.com/http4k/http4k/issues/1221

This change we will also allow to use [openapi-generator](https://github.com/OpenAPITools/openapi-generator) to generate file types e.g. Blob for Typescript.

### CODE REVIEW

File: core/contract/src/main/kotlin/org/http4k/contract/openapi/v3/OpenApi3.kt [hunk 1]
```diff
@@ -315,18 +316,28 @@ class OpenApi3<NODE : Any>(
...
-            ?: message.bodyString().toSchema(definitionId)
+        fun exampleSchemaIsValid(schema: JsonSchema<NODE>) = when (example) {
+            is Array<*>, is Iterable<*> -> !json.fields(schema.node).toMap().containsKey("\$ref")
+            else -> apiRenderer.toSchema(object {}, refModelNamePrefix = schemaPrefix) != schema
+        }
 
-        return SchemaContent(jsonSchema, message.bodyString().safeParse())
+        return when (example) {
+            is InputStream -> NoSchema(
+                schema = json {
```
Comment (daviddenton) [inline core/contract/src/main/kotlin/org/http4k/contract/openapi/v3/OpenApi3.kt:326]: Is there a type we can use instead of manually creating the JSON here?

**Comment by daviddenton** [comment]
Well done on taking this on - it's not exactly simple code!

Just one comment from me, but other than that it looks 👍

File: core/contract/src/main/kotlin/org/http4k/contract/openapi/v3/OpenApi3.kt (hunk 1 above)
Comment (hektorKS) [reply core/contract/src/main/kotlin/org/http4k/contract/openapi/v3/OpenApi3.kt:326]: Hmm, I used the same approach as in other places in this file:
e.g. 
`val noSchema = consumes.map { it.value to NoSchema(json { obj("type" to string(StringParam.value)) }) }`

Comment (hektorKS) [reply core/contract/src/main/kotlin/org/http4k/contract/openapi/v3/OpenApi3.kt:326]: There is space to refactor this code for sure, but probably we prefer small MRs ;)

Comment (daviddenton) [reply core/contract/src/main/kotlin/org/http4k/contract/openapi/v3/OpenApi3.kt:326]: ok - I was just checking and not wanting to go and look!
